---

- hosts: alarm
  gather_facts: no
  become_method: su
  tasks:
    - include_role:
        name: pre-ansible
        apply:
          become: yes
      vars:
        keyring: "archlinuxarm"

    - include_tasks:
        file: roles/common/tasks/users/create-sudo-user.yml
        apply:
          become: yes
      vars:
        username: "muser"
        hostname: "musiverse"
        userpasswd: "$6$lalallasalt$LfVEjZmo0alN6nr67WkOWaM/.N7JDha9rY0FIgJTQsQO2MACqE2tpV9CB9YBhJl1JCvp8MCPP6ALjJdKX5auB1"
        usergroups: [wheel]
        use_sudo: yes


- hosts: musiverse
  vars:
  tasks:
    - include_role:
        name: geerlingguy.swap
        apply:
          become: yes
      vars:
        swap_file_path: "/swapfile"
        swap_file_size_mb: "512"
        swap_swappiness: '1'
        swap_file_state: present
        swap_file_create_command: "fallocate -l {{ swap_file_size_mb }}M {{ swap_file_path }}"
      when: "'musiverse' in inventory_hostname"
      tags: [swap]

    - import_role:
        name: common
      become: yes
      vars:
        username: "muser"
        hostname: "musiverse"
        keyring: "archlinuxarm"
        userpasswd: "$6$lalallasalt$LfVEjZmo0alN6nr67WkOWaM/.N7JDha9rY0FIgJTQsQO2MACqE2tpV9CB9YBhJl1JCvp8MCPP6ALjJdKX5auB1"
        usergroups:
          - wheel
        use_sudo: yes
        create_ssh_keypair: yes
        deluser: "alarm"
        timezone: "Europe/Berlin"
        locale: "de_DE.UTF-8"
        disable_ipv6: yes
        services:
          # service name: containing package
          ntpd: ntp
          cronie: cronie
        packages:
          - ansible
          - pbzip2
          - dnsmasq
          - hostapd
          - ntp      # Todo: enable service
          - cronie   # Todo: enable service
          - sudo
          - rsync
          - git
          - tree
          - base-devel
          - ruby-bundler
          - bind-tools
          - tmux
          - htop
          - jq
      tags: [common]

    - import_role:
        name: musiverse
      become_user: "{{ username }}"
      tags: [musiverse]
      vars:
        musiverse_repo: "https://github.com/Z3NOX/MusiVerse.git"
        musiverse_ansible_repo: "https://github.com/Z3NOX/ansible_MusiVerse.git"
        localSSID: "WifiSSID"
        # create Passphrase using `wpa_passphrase $localSSID`:
        localPSK: "fe49c00ad13a710319387443df8466979b4fe0348dc0f5c74ca2200b84a8279b"
        packages:
          Kinderlieder: {'state': "present", 'name': "Kinderlieder"}
          Schlaflieder: {'state': "present", 'name': "Schlaflieder"}
          Volkslieder: {'state': "absent", 'name': "Volkslieder"}
          Folk_Gospel: {'state': "present", 'name': "Folk & Gospel"}
          Weihnachtslieder: {'state': "absent", 'name': "Weihnachtslieder"}
          Sonstiges: {'state': "present", 'name': "weitere Lieder"}
