---
- name: Create user "{{ username }}"
  user:
    name: "{{ username }}"
    group: "users"
    groups: "{{ usergroups }}"
    password: "{{ userpasswd }}"
    update_password: on_create
    state: present
  become: yes
  tags: [users]

- name: Create ssh keypair for this user
  openssh_keypair:
    path: "/home/{{ username }}/.ssh/id_rsa"
    mode: 0600
    owner: "{{ username }}"
    group: "users"
    comment: "{{ username }}@{{ hostname }}"
  when: create_ssh_keypair is defined and create_ssh_keypair
