---

- debug: msg="{{ lookup('pipe','date \"+%Y-%m-%d %H:%M:%S\"') }}"

- name: stop systemd-resolved time in order for DNSSEC to work.
  raw: systemctl stop systemd-resolved.service

- name: install python
  raw: "pacman-key --init && \
        pacman-key --populate {{ keyring }} &&\
        pacman --noconfirm -Syy && \
        pacman --noconfirm -S python"
  register: raw

  # - debug:
  #     msg: "{{ raw.stdout }}"
