---

- name: write tmux start into bashrc
  blockinfile:
    name: "/home/{{ username }}/.bashrc"
    block: |
      if [ -z "$TMUX" ] && [ -n "$SSH_TTY" ] && [[ $- =~ i ]]; then
          tmux attach-session -t ssh || tmux new-session -s ssh
          exit
      fi
  tags: [install_musiverse]

- name: register overwrite update_musiverse hook with never tag
  command: "echo nonesense"
  register: force_update
  tags: [never]

- name: setup nginx
  import_tasks: nginx-setup.yml
  become_user: root
  become: yes

- name: copy and place static content
  import_tasks: musiverse-static.yml

- name: enroll dynamic content using the github repository
  import_tasks: musiverse-dynamic.yml

- name: setup wifi
  import_tasks: wifi-setup.yml
  become_user: root
  become: yes
