---
- name: include vars
  include_vars:
    file: combine_search.yml
  tags: [always]

- name: write tmux start into bashrc
  blockinfile:
    name: "/home/{{ username }}/.bashrc"
    block: |
      if [ -z "$TMUX" ] && [ -n "$SSH_TTY" ] && [[ $- =~ i ]]; then
          tmux attach-session -t ssh || tmux new-session -s ssh
          exit
      fi
  tags: [install_musiverse]

- name: make sure sytemd-resolved is not enabled to suppress DNSSEC
  service:
    name: systemd-resolved.service
    enabled: "yes"
    state: "stopped"
  become_user: "root"
  become: "yes"
  tags: [dns, systemd]

- name: register overwrite update_musiverse hook with never tag
  command: "echo nonesense"
  register: force_update
  notify:
    - create static search directory
    - generate dynamic site
  tags: [update_musiverse, never]

- name: setup nginx
  import_tasks: nginx-setup.yml
  become_user: root
  become: yes

- name: setup samba
  import_tasks: samba-setup.yml
  become_user: root
  become: yes

- name: clone musiverse ansible repo locally
  git:
    repo: "{{ musiverse_ansible_repo }}"
    dest: "/home/{{ username }}/musiverse-ansible"
    force: yes
  tags: [install_musiverse, git]

- name: copy locally changed ansible playbook
  copy:
    src: "playbook.yml"
    dest: "/home/{{ username }}/musiverse-ansible"
  tags: ["install_musiverse", "git"]

- name: add static packages
  import_tasks: musiverse-static.yml

- debug:
    msg: "basic_combine_command: {{ basic_combine_command }}"
  tags: [static_content]

- name: enroll dynamic content using the github repository
  import_tasks: musiverse-dynamic.yml

- name: setup wifi
  import_tasks: wifi-setup.yml
  become_user: root
  become: yes

- name: setup leds
  import_tasks: configure-leds.yml
  become_user: root
  become: yes

- name: configure onsite musiverse update
  import_tasks: configure-onsite-update.yml

- name: start cronie
  service:
    name: "cronie.service"
    enabled: "yes"
    state: "restarted"
  become_user: "root"
  become: "yes"
  tags: ["cron"]
