- debug:
    msg: "{{ static_content_copied }}"

- name: create bare git repo for files
  git:
    repo: "{{ musiverse_repo }}"
    dest: "/home/{{ username }}/git/musiverse"
    bare: yes
  tags: [update_musiverse, install_musiverse]

- name: clone repo locally
  git:
    repo: "/home/{{ username }}/git/musiverse"
    dest: "/home/{{ username }}/musiverse"
    force: yes
  register: repo_update
  notify: generate dynamic site
  tags: [update_musiverse, install_musiverse]

- name: copy post-receive hook to bare repo
  copy:
    src: "git/post-receive"
    dest: "/home/{{ username }}/git/musiverse/hooks"
    mode: 0755
  tags: [install_musiverse]

- name: copy search merging script to home dir
  copy:
    src: "combine_search_data.py"
    dest: "/home/{{ username }}/"
    mode: 0644
  tags: [install_musiverse]

- name: install bundler packages
  command:
    cmd: "bundler install --path=."
    chdir: "/home/{{ username }}/musiverse"
  when: repo_update.changed or force_update is defined
  tags: [install_musiverse]

