- debug:
    msg: "{{ static_content_copied }}"
  when: static_content_copied is defined

    # - name: create bare git repo for files
    #   git:
    #     repo: "{{ musiverse_repo }}"
    #     dest: "/home/{{ username }}/git/musiverse"
    #     bare: yes
    #   tags: [update_musiverse, install_musiverse]

- name: clone repo locally
  git:
    repo: "{{ musiverse_repo }}"
    dest: "/home/{{ username }}/musiverse"
    force: yes
  register: repo_update
  notify: generate dynamic site
  tags: [install_musiverse, git]

- name: copy search merging script to home dir
  copy:
    src: "combine_search_data.py"
    dest: "/home/{{ username }}/"
    mode: 0644
  tags: [install_musiverse]

- name: install bundler packages
  command:
    cmd: "bundler install --path=."
    chdir: "/home/{{ username }}/musiverse"
  when: repo_update.changed or force_update is defined

- name: update bundler packages
  command:
    cmd: "bundler update"
    chdir: "/home/{{ username }}/musiverse"
