---

- name: create static search directory
  file:
    path: /srv/http/_site_static/assets/js/
    owner: "{{ username }}"
    group: "http"
    state: directory
  become: 'yes'
  become_user: 'root'

- name: copy package overview markdown template
  template:
    src: "Pakete/index.md"
    dest: "/home/{{ username }}/musiverse/Pakete/"
  listen: generate dynamic site

- name: generate dynamic site
  command:
    cmd: "bundler-2.7 exec jekyll build -d /srv/http/_site/"
    chdir: "/home/{{ username }}/musiverse"
  notify:
    - update search data
    - change site permissions

- name: change site permissions
  file:
    dest: "/srv/http/_site"
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: http
    mode: 0774
  become: 'yes'
  become_user: 'root'

- name: add package search data to combine command
  set_fact:
    basic_combine_command: "{{ basic_combine_command + ['/home/' + username +'/_site/assets/js/search-data-' + item.key + '.json'] }}"
  with_dict: "{{ packages }}"
  when: "item.value.state == 'present'"
  listen: update search data

- name: debug combine command
  debug:
    msg: "debug command: {{ basic_combine_command }}"
  listen: update search data

- name: update search data
  command:
    argv: "{{ basic_combine_command }}"
  become: 'yes'
  become_user: 'root'

- name: reboot
  command: "reboot"
  become: yes
