- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  tags: [install]

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
  tags: [install]

- name: Add sudoers users to wheel group
  user: 
    name: "{{ username }}"
    groups: wheel
    append: yes
    state: present
  tags: [users]
