- name: Install required basic packages
  pacman:
    name:
      - cronie
      - sudo
      - base-devel
      - tmux
      - ntp
      - htop
      - atop
      - dialog
      - vim
      - wget
      - curl
      - man
    state: present
  become: yes
  tags:
    - pacman
    - packages
