---
- name: check pacman keyring intitialization
  stat:
      path: "/etc/pacman.d/gnupg"
  register: gnupg
  tags: [pacman]

- name: initialize pacman keyring
  command: "pacman-key --init"
  when: not gnupg.stat.exists
  tags: [pacman]

- name: populate keyring
  command: "pacman-key --populate {{ keyring }}"
  when: not gnupg.stat.exists
  tags: [pacman]
